import type { GraphData, GraphResponse, ExpandResponse, GraphNode, GraphLink } from "./types";

function delay(ms: number) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

function cloneNode(node: GraphNode): GraphNode {
  return {
    ...node,
    industries: node.industries ? [...node.industries] : undefined,
    subsidiaries: node.subsidiaries ? [...node.subsidiaries] : undefined,
    products: node.products ? [...node.products] : undefined,
    categories: node.categories ? [...node.categories] : undefined,
  };
}

function linkEndpointId(endpoint: string | GraphNode): string {
  return typeof endpoint === "string" ? endpoint : endpoint.id;
}

function cloneLink(link: GraphLink): GraphLink {
  return {
    ...link,
    source: linkEndpointId(link.source),
    target: linkEndpointId(link.target),
  };
}

const INITIAL_NODES: GraphNode[] = [
  { id: "stellantis", label: "Stellantis N.V.", type: "company", description: "Multinational automotive manufacturing corporation formed by the 50-50 merger of FCA and PSA Group. Owns 14 automotive brands.", industries: ["Automotive"], headquarters: "Amsterdam, Netherlands", founded: "2021", website: "stellantis.com" },
  { id: "gm", label: "General Motors", type: "company", description: "American multinational automotive manufacturing company. One of the Big Three US automakers.", industries: ["Automotive"], headquarters: "Detroit, Michigan, USA", founded: "1908", website: "gm.com" },
  { id: "ford", label: "Ford Motor Company", type: "company", description: "American multinational automobile manufacturer. Pioneer of mass-production assembly lines.", industries: ["Automotive"], headquarters: "Dearborn, Michigan, USA", founded: "1903", website: "ford.com" },
  { id: "toyota", label: "Toyota Motor Corporation", type: "company", description: "Japanese multinational automotive manufacturer. World's largest automaker by volume.", industries: ["Automotive"], headquarters: "Toyota City, Japan", founded: "1937", website: "global.toyota" },
  { id: "vw-group", label: "Volkswagen Group", type: "company", description: "German multinational automotive manufacturing company. Europe's largest automaker, owning 12 brands from volume to ultra-luxury.", industries: ["Automotive"], headquarters: "Wolfsburg, Germany", founded: "1937" },
  { id: "bmw", label: "BMW Group", type: "company", description: "German multinational manufacturer of luxury vehicles and motorcycles.", industries: ["Automotive", "Luxury", "Motorcycles"], headquarters: "Munich, Germany", founded: "1916", website: "bmwgroup.com" },
  { id: "mercedes", label: "Mercedes-Benz Group", type: "company", description: "German multinational automotive corporation. Inventor of the modern automobile.", industries: ["Automotive", "Luxury", "Commercial Vehicles"], headquarters: "Stuttgart, Germany", founded: "1926" },
  { id: "honda", label: "Honda Motor Co.", type: "company", description: "Japanese multinational manufacturer of automobiles, motorcycles, and power equipment.", industries: ["Automotive", "Motorcycles"], headquarters: "Tokyo, Japan", founded: "1948" },
  { id: "hyundai-motor", label: "Hyundai Motor Group", type: "company", description: "South Korean multinational automotive manufacturer. Parent of Hyundai, Kia, and Genesis.", industries: ["Automotive"], headquarters: "Seoul, South Korea", founded: "1967" },
  { id: "renault-nissan", label: "Renault–Nissan–Mitsubishi Alliance", type: "company", description: "Franco-Japanese strategic alliance. The world's largest seller of light-duty vehicles by volume.", industries: ["Automotive"], headquarters: "Yokohama, Japan", founded: "1999" },
  { id: "tesla", label: "Tesla, Inc.", type: "company", description: "American multinational automotive and clean energy company. Leader in battery electric vehicles.", industries: ["Automotive", "Electric Vehicles", "Energy"], headquarters: "Austin, Texas, USA", founded: "2003", website: "tesla.com" },
  { id: "geely", label: "Geely Holding Group", type: "company", description: "Chinese automotive group with global brand holdings across mass-market, premium, and electric mobility.", industries: ["Automotive", "Electric Vehicles"], headquarters: "Hangzhou, China", founded: "1986" },
  { id: "mazda", label: "Mazda Motor Corporation", type: "company", description: "Japanese automaker known for driver-focused vehicles and Skyactiv engineering.", industries: ["Automotive"], headquarters: "Hiroshima, Japan", founded: "1920" },
  { id: "byd", label: "BYD Auto", type: "company", description: "Chinese automaker and battery manufacturer with a broad plug-in hybrid and battery electric lineup.", industries: ["Automotive", "Electric Vehicles", "Batteries"], headquarters: "Shenzhen, China", founded: "2003" },
  { id: "rivian", label: "Rivian", type: "company", description: "American electric vehicle manufacturer focused on adventure-oriented trucks, SUVs, and commercial vans.", industries: ["Automotive", "Electric Vehicles"], headquarters: "Irvine, California, USA", founded: "2009" },
  { id: "lucid", label: "Lucid Motors", type: "company", description: "American luxury electric vehicle manufacturer focused on high-efficiency premium sedans and SUVs.", industries: ["Automotive", "Electric Vehicles", "Luxury"], headquarters: "Newark, California, USA", founded: "2007" },
  { id: "ram", label: "RAM Trucks", type: "brand", description: "American brand of light to mid-weight trucks and vans, a division of Stellantis.", industries: ["Automotive", "Trucks"], parentCompany: "Stellantis" },
  { id: "jeep", label: "Jeep", type: "brand", description: "American automobile brand known for SUVs and off-road vehicles, a division of Stellantis.", industries: ["Automotive", "SUVs"], parentCompany: "Stellantis" },
  { id: "dodge", label: "Dodge", type: "brand", description: "American automobile brand known for performance cars and SUVs, a division of Stellantis.", industries: ["Automotive", "Performance"], parentCompany: "Stellantis" },
  { id: "chrysler", label: "Chrysler", type: "brand", description: "American luxury automobile brand, a division of Stellantis.", industries: ["Automotive", "Luxury"], parentCompany: "Stellantis" },
  { id: "fiat", label: "Fiat", type: "brand", description: "Italian automobile manufacturer, a subsidiary of Stellantis.", industries: ["Automotive", "Compact"], parentCompany: "Stellantis", headquarters: "Turin, Italy", founded: "1899" },
  { id: "peugeot", label: "Peugeot", type: "brand", description: "French automotive brand, a subsidiary of Stellantis.", industries: ["Automotive"], parentCompany: "Stellantis", headquarters: "Sochaux, France", founded: "1810" },
  { id: "maserati", label: "Maserati", type: "brand", description: "Italian luxury vehicle manufacturer, a subsidiary of Stellantis.", industries: ["Automotive", "Luxury"], parentCompany: "Stellantis", headquarters: "Modena, Italy", founded: "1914" },
  { id: "alfa-romeo", label: "Alfa Romeo", type: "brand", description: "Italian premium automobile manufacturer, a subsidiary of Stellantis.", industries: ["Automotive", "Luxury"], parentCompany: "Stellantis", headquarters: "Turin, Italy", founded: "1910" },
  { id: "chevrolet", label: "Chevrolet", type: "brand", description: "American automobile division of General Motors.", industries: ["Automotive"], parentCompany: "General Motors", founded: "1911" },
  { id: "gmc", label: "GMC", type: "brand", description: "American vehicle division of General Motors focused on trucks and utility vehicles.", industries: ["Automotive", "Trucks"], parentCompany: "General Motors" },
  { id: "cadillac", label: "Cadillac", type: "brand", description: "American luxury automobile brand, a division of General Motors.", industries: ["Automotive", "Luxury"], parentCompany: "General Motors", headquarters: "Detroit, Michigan, USA", founded: "1902" },
  { id: "buick", label: "Buick", type: "brand", description: "American automobile brand, a division of General Motors.", industries: ["Automotive", "Luxury"], parentCompany: "General Motors" },
  { id: "audi", label: "Audi", type: "brand", description: "German luxury automotive manufacturer, a subsidiary of Volkswagen Group.", industries: ["Automotive", "Luxury"], parentCompany: "Volkswagen Group", headquarters: "Ingolstadt, Germany", founded: "1909" },
  { id: "porsche", label: "Porsche", type: "brand", description: "German luxury sports car manufacturer, a subsidiary of Volkswagen Group.", industries: ["Automotive", "Luxury", "Performance"], parentCompany: "Volkswagen Group", headquarters: "Stuttgart, Germany", founded: "1931" },
  { id: "vw", label: "Volkswagen", type: "brand", description: "German automotive manufacturer, the core brand of Volkswagen Group.", industries: ["Automotive"], parentCompany: "Volkswagen Group", headquarters: "Wolfsburg, Germany", founded: "1937" },
  { id: "lamborghini", label: "Lamborghini", type: "brand", description: "Italian luxury sports car manufacturer, owned by Volkswagen Group through Audi.", industries: ["Automotive", "Ultra-Luxury", "Performance"], parentCompany: "Volkswagen Group", headquarters: "Sant'Agata Bolognese, Italy", founded: "1963" },
  { id: "bentley", label: "Bentley", type: "brand", description: "British luxury automobile manufacturer, owned by Volkswagen Group.", industries: ["Automotive", "Ultra-Luxury"], parentCompany: "Volkswagen Group", headquarters: "Crewe, England", founded: "1919" },
  { id: "mini", label: "Mini", type: "brand", description: "British automotive marque owned by BMW, known for the iconic Mini Cooper.", industries: ["Automotive", "Compact"], parentCompany: "BMW Group" },
  { id: "rolls-royce", label: "Rolls-Royce", type: "brand", description: "British ultra-luxury automobile manufacturer, owned by BMW Group.", industries: ["Automotive", "Ultra-Luxury"], parentCompany: "BMW Group", headquarters: "Goodwood, England", founded: "1904" },
  { id: "lexus", label: "Lexus", type: "brand", description: "Japanese luxury vehicle division of Toyota.", industries: ["Automotive", "Luxury"], parentCompany: "Toyota", headquarters: "Nagoya, Japan", founded: "1989" },
  { id: "kia", label: "Kia", type: "brand", description: "South Korean automobile manufacturer, a subsidiary of Hyundai Motor Group.", industries: ["Automotive"], parentCompany: "Hyundai Motor Group" },
  { id: "genesis", label: "Genesis", type: "brand", description: "South Korean luxury vehicle division of Hyundai Motor Group.", industries: ["Automotive", "Luxury"], parentCompany: "Hyundai Motor Group", founded: "2015" },
  { id: "nissan", label: "Nissan", type: "brand", description: "Japanese automobile manufacturer, part of the Renault–Nissan–Mitsubishi Alliance.", industries: ["Automotive"], headquarters: "Yokohama, Japan", founded: "1933" },
  { id: "renault", label: "Renault", type: "brand", description: "French automobile manufacturer, lead member of the Renault–Nissan–Mitsubishi Alliance.", industries: ["Automotive"], headquarters: "Boulogne-Billancourt, France", founded: "1899" },
  { id: "mitsubishi-motors", label: "Mitsubishi Motors", type: "brand", description: "Japanese multinational automotive manufacturer, part of the Alliance.", industries: ["Automotive"], headquarters: "Tokyo, Japan", founded: "1970" },
  { id: "subaru", label: "Subaru", type: "brand", description: "Japanese automobile manufacturer known for all-wheel drive vehicles and boxer engines.", industries: ["Automotive", "AWD"], headquarters: "Tokyo, Japan", founded: "1953" },
  { id: "volvo-cars", label: "Volvo Cars", type: "brand", description: "Swedish premium automotive brand known for safety, electrification, and Scandinavian design.", industries: ["Automotive", "Luxury", "Electric Vehicles"], parentCompany: "Geely Holding Group", headquarters: "Gothenburg, Sweden", founded: "1927" },
  { id: "polestar", label: "Polestar", type: "brand", description: "Electric performance brand connected to Volvo Cars and Geely.", industries: ["Automotive", "Electric Vehicles", "Performance"], parentCompany: "Geely Holding Group", headquarters: "Gothenburg, Sweden", founded: "2017" },
  { id: "automotive", label: "Automotive", type: "category", description: "The automotive industry encompasses design, development, and manufacturing of motor vehicles." },
  { id: "pickup-truck", label: "Pickup Truck", type: "category", description: "Light-duty truck with an open cargo area." },
  { id: "suv", label: "SUV", type: "category", description: "Sport Utility Vehicle — a rugged automotive combining passenger and cargo space." },
  { id: "luxury", label: "Luxury Vehicle", type: "category", description: "Premium vehicles with enhanced comfort, quality, and features." },
  { id: "electric-vehicle", label: "Electric Vehicle", type: "category", description: "Vehicles powered by electric motors and battery packs." },
  { id: "off-road", label: "Off-Road Vehicle", type: "category", description: "Vehicles designed for off-highway and rugged terrain use." },
  { id: "sedan", label: "Sedan", type: "category", description: "Passenger car with a three-box configuration." },
  { id: "sports-car", label: "Sports Car", type: "category", description: "Performance-oriented automobiles designed for speed and handling." },
  { id: "commercial-vehicle", label: "Commercial Vehicle", type: "category", description: "Vehicles designed for commercial and fleet use." },
  { id: "muscle-car", label: "Muscle Car", type: "category", description: "American high-performance automobiles with powerful V8 engines." },
  { id: "hybrid", label: "Hybrid Vehicle", type: "category", description: "Vehicles combining internal-combustion powertrains with electric motors." },
  { id: "compact", label: "Compact Car", type: "category", description: "Smaller passenger cars optimized for efficiency, city use, and accessible pricing." },
  { id: "hatchback", label: "Hatchback", type: "category", description: "Passenger cars with a rear hatch and flexible cargo area." },
  { id: "commercial-van", label: "Commercial Van", type: "category", description: "Van platforms used for delivery, trades, and fleet operations." },
  { id: "charging-infrastructure", label: "Charging Infrastructure", type: "category", description: "Public, home, and fleet EV charging networks and hardware." },
  { id: "autonomous-driving", label: "Autonomous Driving", type: "category", description: "Driver assistance, hands-free driving, and autonomy-related vehicle capabilities." },
  { id: "software-defined-vehicle", label: "Software-defined Vehicle", type: "category", description: "Vehicles whose features, UX, and capabilities are increasingly shaped by software and OTA updates." },
  { id: "battery-supply-chain", label: "Battery Supply Chain", type: "category", description: "Battery cells, minerals, pack manufacturing, and sourcing narratives behind EV marketing." },
  { id: "ram-1500", label: "RAM 1500", type: "product", description: "Full-size pickup truck, flagship of the RAM brand.", categories: ["Pickup Truck"] },
  { id: "jeep-grand-cherokee", label: "Jeep Grand Cherokee", type: "product", description: "Mid-size luxury SUV produced by Jeep.", categories: ["SUV", "Luxury"] },
  { id: "f150", label: "Ford F-150", type: "product", description: "Full-size pickup truck, best-selling vehicle in the US.", categories: ["Pickup Truck"] },
  { id: "model-y", label: "Tesla Model Y", type: "product", description: "Compact crossover SUV, Tesla's best-selling model.", categories: ["SUV", "Electric Vehicle"] },
  { id: "camry", label: "Toyota Camry", type: "product", description: "Mid-size sedan, one of the best-selling cars globally.", categories: ["Sedan"] },
  { id: "corvette", label: "Chevrolet Corvette", type: "product", description: "American sports car icon by Chevrolet.", categories: ["Sports Car"] },
  { id: "mustang", label: "Ford Mustang", type: "product", description: "American pony car/muscle car, in production since 1964.", categories: ["Muscle Car"] },
  { id: "porsche-911", label: "Porsche 911", type: "product", description: "Legendary rear-engine sports car by Porsche.", categories: ["Sports Car", "Luxury"] },
  { id: "model-3", label: "Tesla Model 3", type: "product", description: "Compact executive sedan by Tesla, the world's best-selling plug-in car.", categories: ["Sedan", "Electric Vehicle"] },
  { id: "cybertruck", label: "Tesla Cybertruck", type: "product", description: "Battery electric pickup truck with stainless steel exoskeleton.", categories: ["Pickup Truck", "Electric Vehicle"] },
  { id: "golf", label: "Volkswagen Golf", type: "product", description: "Compact hatchback, VW's best-selling model worldwide.", categories: ["Compact", "Hatchback"] },
  { id: "civic", label: "Honda Civic", type: "product", description: "Compact car, one of the best-selling automobiles globally.", categories: ["Sedan", "Compact"] },
  { id: "mazda-cx5", label: "Mazda CX-5", type: "product", description: "Compact crossover SUV positioned around driving feel and premium mainstream interiors.", categories: ["SUV", "Compact"] },
  { id: "volvo-ex90", label: "Volvo EX90", type: "product", description: "Electric three-row SUV positioned around safety, family utility, and premium technology.", categories: ["SUV", "Electric Vehicle", "Luxury"] },
  { id: "polestar-2", label: "Polestar 2", type: "product", description: "Electric fastback by Polestar with performance and design-led positioning.", categories: ["Electric Vehicle", "Luxury"] },
  { id: "rivian-r1t", label: "Rivian R1T", type: "product", description: "Electric adventure pickup truck with outdoor and utility-oriented positioning.", categories: ["Pickup Truck", "Electric Vehicle", "Off-road"] },
  { id: "lucid-air", label: "Lucid Air", type: "product", description: "Luxury electric sedan focused on efficiency, range, and premium cabin experience.", categories: ["Sedan", "Electric Vehicle", "Luxury"] },
  { id: "byd-seal", label: "BYD Seal", type: "product", description: "Battery electric sedan by BYD with mainstream EV positioning.", categories: ["Sedan", "Electric Vehicle"] },
  { id: "toyota-bz4x", label: "Toyota bZ4X", type: "product", description: "Battery electric SUV in Toyota's bZ electric lineup.", categories: ["SUV", "Electric Vehicle"] },
  { id: "honda-prologue", label: "Honda Prologue", type: "product", description: "Battery electric SUV positioned as Honda's mainstream EV entry.", categories: ["SUV", "Electric Vehicle"] },
  { id: "chevy-equinox-ev", label: "Chevrolet Equinox EV", type: "product", description: "Electric compact SUV positioned for mass-market EV adoption.", categories: ["SUV", "Electric Vehicle"] },
  { id: "future-ev-price-compression", label: "EV Price Compression", type: "future", description: "Future signal: a forward edge the graph can hand to an agentic workflow to track EV ads shifting from range leadership to discounts, lease offers, tax-credit language, and affordability claims." },
  { id: "future-charging-confidence", label: "Charging Confidence", type: "future", description: "Future signal: an ever-expanding agentic path for monitoring how brands reduce charging anxiety through network access, home-charging bundles, route planning, and fleet uptime claims." },
  { id: "future-software-defined-ux", label: "Software-defined UX", type: "future", description: "Future signal: a queued agentic expansion path for OTA updates, hands-free driving claims, subscription features, cockpit AI, and app-connected ownership narratives." },
  { id: "future-battery-localization", label: "Battery Localization", type: "future", description: "Future signal: a forward-looking graph edge for sourcing, domestic assembly, chemistry, warranty, and battery-health claims that may shape EV ad messaging." },
  { id: "future-offroad-positioning", label: "Off-road Identity Shift", type: "future", description: "Future signal: agentic work can expand from this node into ruggedness, trail capability, adventure lifestyle, and durability claims across SUVs, trucks, and electric adventure vehicles." },
];

const INITIAL_LINKS: GraphLink[] = [
  { source: "stellantis", target: "ram", label: "owns", strength: 1 },
  { source: "stellantis", target: "jeep", label: "owns", strength: 1 },
  { source: "stellantis", target: "dodge", label: "owns", strength: 1 },
  { source: "stellantis", target: "chrysler", label: "owns", strength: 1 },
  { source: "stellantis", target: "fiat", label: "owns", strength: 1 },
  { source: "stellantis", target: "peugeot", label: "owns", strength: 1 },
  { source: "stellantis", target: "maserati", label: "owns", strength: 1 },
  { source: "stellantis", target: "alfa-romeo", label: "owns", strength: 1 },
  { source: "gm", target: "chevrolet", label: "owns", strength: 1 },
  { source: "gm", target: "gmc", label: "owns", strength: 1 },
  { source: "gm", target: "cadillac", label: "owns", strength: 1 },
  { source: "gm", target: "buick", label: "owns", strength: 1 },
  { source: "vw-group", target: "audi", label: "owns", strength: 1 },
  { source: "vw-group", target: "porsche", label: "owns", strength: 1 },
  { source: "vw-group", target: "vw", label: "owns", strength: 1 },
  { source: "vw-group", target: "lamborghini", label: "owns", strength: 1 },
  { source: "vw-group", target: "bentley", label: "owns", strength: 1 },
  { source: "bmw", target: "mini", label: "owns", strength: 1 },
  { source: "bmw", target: "rolls-royce", label: "owns", strength: 1 },
  { source: "toyota", target: "lexus", label: "owns", strength: 1 },
  { source: "hyundai-motor", target: "kia", label: "owns", strength: 1 },
  { source: "hyundai-motor", target: "genesis", label: "owns", strength: 1 },
  { source: "renault-nissan", target: "nissan", label: "alliance", strength: 0.7 },
  { source: "renault-nissan", target: "renault", label: "alliance", strength: 0.7 },
  { source: "renault-nissan", target: "mitsubishi-motors", label: "alliance", strength: 0.6 },
  { source: "renault", target: "nissan", label: "strategic_partner", strength: 0.5 },
  { source: "geely", target: "volvo-cars", label: "owns", strength: 1 },
  { source: "geely", target: "polestar", label: "controls", strength: 0.8 },
  { source: "ram", target: "pickup-truck", label: "category", strength: 0.8 },
  { source: "jeep", target: "suv", label: "category", strength: 0.8 },
  { source: "jeep", target: "off-road", label: "category", strength: 0.8 },
  { source: "dodge", target: "muscle-car", label: "category", strength: 0.7 },
  { source: "chrysler", target: "luxury", label: "category", strength: 0.7 },
  { source: "audi", target: "luxury", label: "category", strength: 0.8 },
  { source: "porsche", target: "sports-car", label: "category", strength: 0.9 },
  { source: "porsche", target: "luxury", label: "category", strength: 0.8 },
  { source: "cadillac", target: "luxury", label: "category", strength: 0.8 },
  { source: "rolls-royce", target: "luxury", label: "category", strength: 1 },
  { source: "lamborghini", target: "luxury", label: "category", strength: 0.9 },
  { source: "lamborghini", target: "sports-car", label: "category", strength: 0.9 },
  { source: "bentley", target: "luxury", label: "category", strength: 0.9 },
  { source: "maserati", target: "luxury", label: "category", strength: 0.8 },
  { source: "alfa-romeo", target: "luxury", label: "category", strength: 0.7 },
  { source: "lexus", target: "luxury", label: "category", strength: 0.8 },
  { source: "genesis", target: "luxury", label: "category", strength: 0.7 },
  { source: "mini", target: "sedan", label: "category", strength: 0.6 },
  { source: "fiat", target: "sedan", label: "category", strength: 0.5 },
  { source: "vw", target: "sedan", label: "category", strength: 0.5 },
  { source: "subaru", target: "off-road", label: "category", strength: 0.7 },
  { source: "subaru", target: "suv", label: "category", strength: 0.6 },
  { source: "buick", target: "luxury", label: "category", strength: 0.7 },
  { source: "gmc", target: "pickup-truck", label: "category", strength: 0.7 },
  { source: "mazda", target: "suv", label: "category", strength: 0.7 },
  { source: "mazda", target: "compact", label: "category", strength: 0.6 },
  { source: "volvo-cars", target: "suv", label: "category", strength: 0.7 },
  { source: "volvo-cars", target: "luxury", label: "category", strength: 0.8 },
  { source: "volvo-cars", target: "electric-vehicle", label: "category", strength: 0.7 },
  { source: "polestar", target: "electric-vehicle", label: "category", strength: 0.9 },
  { source: "polestar", target: "luxury", label: "category", strength: 0.7 },
  { source: "byd", target: "electric-vehicle", label: "category", strength: 0.9 },
  { source: "byd", target: "hybrid", label: "category", strength: 0.7 },
  { source: "rivian", target: "pickup-truck", label: "category", strength: 0.8 },
  { source: "rivian", target: "off-road", label: "category", strength: 0.8 },
  { source: "lucid", target: "luxury", label: "category", strength: 0.9 },
  { source: "tesla", target: "charging-infrastructure", label: "category", strength: 0.8 },
  { source: "tesla", target: "software-defined-vehicle", label: "category", strength: 0.8 },
  { source: "ram", target: "ram-1500", label: "produces", strength: 0.9 },
  { source: "jeep", target: "jeep-grand-cherokee", label: "produces", strength: 0.9 },
  { source: "ford", target: "f150", label: "produces", strength: 0.9 },
  { source: "ford", target: "mustang", label: "produces", strength: 0.9 },
  { source: "chevrolet", target: "corvette", label: "produces", strength: 0.9 },
  { source: "porsche", target: "porsche-911", label: "produces", strength: 1 },
  { source: "tesla", target: "model-y", label: "produces", strength: 0.9 },
  { source: "tesla", target: "model-3", label: "produces", strength: 0.9 },
  { source: "tesla", target: "cybertruck", label: "produces", strength: 0.9 },
  { source: "toyota", target: "camry", label: "produces", strength: 0.9 },
  { source: "vw", target: "golf", label: "produces", strength: 0.9 },
  { source: "honda", target: "civic", label: "produces", strength: 0.9 },
  { source: "mazda", target: "mazda-cx5", label: "produces", strength: 0.9 },
  { source: "volvo-cars", target: "volvo-ex90", label: "produces", strength: 0.9 },
  { source: "polestar", target: "polestar-2", label: "produces", strength: 0.9 },
  { source: "rivian", target: "rivian-r1t", label: "produces", strength: 0.9 },
  { source: "lucid", target: "lucid-air", label: "produces", strength: 0.9 },
  { source: "byd", target: "byd-seal", label: "produces", strength: 0.9 },
  { source: "toyota", target: "toyota-bz4x", label: "produces", strength: 0.8 },
  { source: "honda", target: "honda-prologue", label: "produces", strength: 0.8 },
  { source: "chevrolet", target: "chevy-equinox-ev", label: "produces", strength: 0.8 },
  { source: "pickup-truck", target: "ram-1500", label: "includes", strength: 0.7 },
  { source: "pickup-truck", target: "f150", label: "includes", strength: 0.7 },
  { source: "pickup-truck", target: "cybertruck", label: "includes", strength: 0.7 },
  { source: "suv", target: "jeep-grand-cherokee", label: "includes", strength: 0.7 },
  { source: "suv", target: "model-y", label: "includes", strength: 0.7 },
  { source: "luxury", target: "porsche-911", label: "includes", strength: 0.7 },
  { source: "sports-car", target: "corvette", label: "includes", strength: 0.7 },
  { source: "sports-car", target: "porsche-911", label: "includes", strength: 0.7 },
  { source: "muscle-car", target: "mustang", label: "includes", strength: 0.8 },
  { source: "electric-vehicle", target: "model-y", label: "includes", strength: 0.7 },
  { source: "electric-vehicle", target: "model-3", label: "includes", strength: 0.7 },
  { source: "electric-vehicle", target: "cybertruck", label: "includes", strength: 0.7 },
  { source: "sedan", target: "camry", label: "includes", strength: 0.6 },
  { source: "sedan", target: "model-3", label: "includes", strength: 0.6 },
  { source: "sedan", target: "civic", label: "includes", strength: 0.6 },
  { source: "sedan", target: "golf", label: "includes", strength: 0.5 },
  { source: "sedan", target: "lucid-air", label: "includes", strength: 0.6 },
  { source: "sedan", target: "byd-seal", label: "includes", strength: 0.6 },
  { source: "compact", target: "golf", label: "includes", strength: 0.7 },
  { source: "compact", target: "civic", label: "includes", strength: 0.7 },
  { source: "compact", target: "mazda-cx5", label: "includes", strength: 0.5 },
  { source: "hatchback", target: "golf", label: "includes", strength: 0.8 },
  { source: "suv", target: "mazda-cx5", label: "includes", strength: 0.7 },
  { source: "suv", target: "volvo-ex90", label: "includes", strength: 0.7 },
  { source: "suv", target: "toyota-bz4x", label: "includes", strength: 0.7 },
  { source: "suv", target: "honda-prologue", label: "includes", strength: 0.7 },
  { source: "suv", target: "chevy-equinox-ev", label: "includes", strength: 0.7 },
  { source: "luxury", target: "volvo-ex90", label: "includes", strength: 0.7 },
  { source: "luxury", target: "polestar-2", label: "includes", strength: 0.7 },
  { source: "luxury", target: "lucid-air", label: "includes", strength: 0.8 },
  { source: "pickup-truck", target: "rivian-r1t", label: "includes", strength: 0.7 },
  { source: "off-road", target: "rivian-r1t", label: "includes", strength: 0.7 },
  { source: "electric-vehicle", target: "volvo-ex90", label: "includes", strength: 0.7 },
  { source: "electric-vehicle", target: "polestar-2", label: "includes", strength: 0.7 },
  { source: "electric-vehicle", target: "rivian-r1t", label: "includes", strength: 0.7 },
  { source: "electric-vehicle", target: "lucid-air", label: "includes", strength: 0.7 },
  { source: "electric-vehicle", target: "byd-seal", label: "includes", strength: 0.7 },
  { source: "electric-vehicle", target: "toyota-bz4x", label: "includes", strength: 0.7 },
  { source: "electric-vehicle", target: "honda-prologue", label: "includes", strength: 0.7 },
  { source: "electric-vehicle", target: "chevy-equinox-ev", label: "includes", strength: 0.7 },
  { source: "stellantis", target: "automotive", label: "operates_in", strength: 0.5 },
  { source: "gm", target: "automotive", label: "operates_in", strength: 0.5 },
  { source: "ford", target: "automotive", label: "operates_in", strength: 0.5 },
  { source: "toyota", target: "automotive", label: "operates_in", strength: 0.5 },
  { source: "vw-group", target: "automotive", label: "operates_in", strength: 0.5 },
  { source: "bmw", target: "automotive", label: "operates_in", strength: 0.5 },
  { source: "mercedes", target: "automotive", label: "operates_in", strength: 0.5 },
  { source: "tesla", target: "electric-vehicle", label: "operates_in", strength: 0.8 },
  { source: "geely", target: "automotive", label: "operates_in", strength: 0.5 },
  { source: "geely", target: "electric-vehicle", label: "operates_in", strength: 0.6 },
  { source: "mazda", target: "automotive", label: "operates_in", strength: 0.5 },
  { source: "byd", target: "electric-vehicle", label: "operates_in", strength: 0.8 },
  { source: "rivian", target: "electric-vehicle", label: "operates_in", strength: 0.8 },
  { source: "lucid", target: "electric-vehicle", label: "operates_in", strength: 0.8 },
  { source: "lucid", target: "luxury", label: "operates_in", strength: 0.7 },
  { source: "hyundai-motor", target: "automotive", label: "operates_in", strength: 0.5 },
  { source: "renault-nissan", target: "automotive", label: "operates_in", strength: 0.5 },
  { source: "honda", target: "automotive", label: "operates_in", strength: 0.5 },
  { source: "stellantis", target: "pickup-truck", label: "operates_in", strength: 0.4 },
  { source: "stellantis", target: "suv", label: "operates_in", strength: 0.4 },
  { source: "gm", target: "pickup-truck", label: "operates_in", strength: 0.4 },
  { source: "gm", target: "suv", label: "operates_in", strength: 0.4 },
  { source: "vw-group", target: "luxury", label: "operates_in", strength: 0.4 },
  { source: "bmw", target: "luxury", label: "operates_in", strength: 0.6 },
  { source: "mercedes", target: "luxury", label: "operates_in", strength: 0.6 },
  { source: "electric-vehicle", target: "future-ev-price-compression", label: "future_signal", strength: 0.55 },
  { source: "charging-infrastructure", target: "future-charging-confidence", label: "future_signal", strength: 0.55 },
  { source: "autonomous-driving", target: "future-software-defined-ux", label: "future_signal", strength: 0.55 },
  { source: "software-defined-vehicle", target: "future-software-defined-ux", label: "future_signal", strength: 0.6 },
  { source: "battery-supply-chain", target: "future-battery-localization", label: "future_signal", strength: 0.55 },
  { source: "off-road", target: "future-offroad-positioning", label: "future_signal", strength: 0.65 },
  { source: "pickup-truck", target: "future-offroad-positioning", label: "future_signal", strength: 0.45 },
  { source: "tesla", target: "future-software-defined-ux", label: "agentic_input", strength: 0.45 },
  { source: "gm", target: "autonomous-driving", label: "operates_in", strength: 0.45 },
  { source: "mercedes", target: "autonomous-driving", label: "operates_in", strength: 0.45 },
  { source: "byd", target: "future-battery-localization", label: "agentic_input", strength: 0.45 },
  { source: "rivian-r1t", target: "future-offroad-positioning", label: "agentic_input", strength: 0.55 },
  { source: "lucid-air", target: "future-ev-price-compression", label: "agentic_input", strength: 0.45 },
];

const EXPANSIONS: Record<string, GraphData> = {
  "ram": {
    nodes: [
      { id: "ram-trx", label: "RAM 1500 TRX", type: "product", description: "High-performance off-road pickup truck.", categories: ["Pickup Truck", "Performance"] },
      { id: "ram-promaster", label: "RAM ProMaster", type: "product", description: "Full-size van used for commercial applications.", categories: ["Commercial Vehicle"] },
      { id: "ram-classic", label: "RAM 1500 Classic", type: "product", description: "Previous-generation RAM 1500 sold alongside the newer model.", categories: ["Pickup Truck"] },
      { id: "ram-2500", label: "RAM 2500", type: "product", description: "Heavy-duty pickup truck in the RAM lineup.", categories: ["Pickup Truck"] },
      { id: "ram-3500", label: "RAM 3500", type: "product", description: "Extreme-duty pickup truck for maximum towing capacity.", categories: ["Pickup Truck", "Commercial Vehicle"] },
    ],
    links: [
      { source: "ram", target: "ram-trx", label: "produces", strength: 0.9 },
      { source: "ram", target: "ram-promaster", label: "produces", strength: 0.9 },
      { source: "ram", target: "ram-classic", label: "produces", strength: 0.9 },
      { source: "ram", target: "ram-2500", label: "produces", strength: 0.9 },
      { source: "ram", target: "ram-3500", label: "produces", strength: 0.9 },
      { source: "pickup-truck", target: "ram-trx", label: "includes", strength: 0.7 },
      { source: "ram", target: "commercial-vehicle", label: "category", strength: 0.5 },
      { source: "commercial-vehicle", target: "ram-promaster", label: "includes", strength: 0.7 },
      { source: "pickup-truck", target: "ram-2500", label: "includes", strength: 0.7 },
      { source: "pickup-truck", target: "ram-3500", label: "includes", strength: 0.7 },
    ],
  },
  "stellantis": {
    nodes: [
      { id: "citroen", label: "Citroën", type: "brand", description: "French automobile manufacturer, a subsidiary of Stellantis.", industries: ["Automotive"], parentCompany: "Stellantis" },
      { id: "ds", label: "DS Automobiles", type: "brand", description: "French luxury vehicle manufacturer, a subsidiary of Stellantis.", industries: ["Automotive", "Luxury"], parentCompany: "Stellantis" },
      { id: "opel", label: "Opel", type: "brand", description: "German automobile manufacturer, a subsidiary of Stellantis.", industries: ["Automotive"], parentCompany: "Stellantis" },
      { id: "leapmotor", label: "Leapmotor", type: "subsidiary", description: "Chinese EV manufacturer, Stellantis holds a significant stake for international expansion.", industries: ["Automotive", "Electric Vehicles"], parentCompany: "Stellantis" },
      { id: "abarth", label: "Abarth", type: "subsidiary", description: "Italian performance car brand, a subsidiary of Stellantis.", industries: ["Automotive", "Performance"], parentCompany: "Stellantis" },
      { id: "fca", label: "Fiat Chrysler Automobiles", type: "company", description: "Italo-American multinational, predecessor of Stellantis (merged 2021).", industries: ["Automotive"], headquarters: "London, UK", founded: "2014" },
      { id: "psa", label: "PSA Group", type: "company", description: "French multinational, predecessor of Stellantis (merged 2021).", industries: ["Automotive"], headquarters: "Rueil-Malmaison, France", founded: "1976" },
    ],
    links: [
      { source: "stellantis", target: "citroen", label: "owns", strength: 1 },
      { source: "stellantis", target: "ds", label: "owns", strength: 1 },
      { source: "stellantis", target: "opel", label: "owns", strength: 1 },
      { source: "stellantis", target: "leapmotor", label: "partnership", strength: 0.6 },
      { source: "stellantis", target: "abarth", label: "owns", strength: 1 },
      { source: "fca", target: "stellantis", label: "merged_into", strength: 0.7 },
      { source: "psa", target: "stellantis", label: "merged_into", strength: 0.7 },
      { source: "ds", target: "luxury", label: "category", strength: 0.7 },
      { source: "opel", target: "automotive", label: "operates_in", strength: 0.5 },
      { source: "citroen", target: "automotive", label: "operates_in", strength: 0.5 },
    ],
  },
  "vw-group": {
    nodes: [
      { id: "skoda", label: "Škoda", type: "brand", description: "Czech automobile manufacturer, a subsidiary of Volkswagen Group.", industries: ["Automotive"], parentCompany: "Volkswagen Group" },
      { id: "seat", label: "SEAT/CUPRA", type: "brand", description: "Spanish automobile manufacturer, a subsidiary of Volkswagen Group.", industries: ["Automotive"], parentCompany: "Volkswagen Group" },
      { id: "bugatti", label: "Bugatti", type: "brand", description: "French hypercar manufacturer, formerly owned by VW Group, now under Rimac.", industries: ["Automotive", "Hypercar"] },
      { id: "vw-golf", label: "Volkswagen Golf", type: "product", description: "Compact hatchback, VW's best-selling model worldwide.", categories: ["Compact", "Hatchback"] },
      { id: "audi-a4", label: "Audi A4", type: "product", description: "Compact executive sedan by Audi.", categories: ["Sedan", "Luxury"] },
      { id: "porsche-taycan", label: "Porsche Taycan", type: "product", description: "Fully electric luxury sports sedan by Porsche.", categories: ["Electric Vehicle", "Luxury"] },
      { id: "lamborghini-huracan", label: "Lamborghini Huracán", type: "product", description: "Mid-engine sports car by Lamborghini.", categories: ["Sports Car", "Luxury"] },
      { id: "bentley-continental", label: "Bentley Continental GT", type: "product", description: "Grand tourer by Bentley, ultra-luxury coupe.", categories: ["Luxury", "Grand Tourer"] },
    ],
    links: [
      { source: "vw-group", target: "skoda", label: "owns", strength: 1 },
      { source: "vw-group", target: "seat", label: "owns", strength: 1 },
      { source: "vw", target: "vw-golf", label: "produces", strength: 0.9 },
      { source: "audi", target: "audi-a4", label: "produces", strength: 0.9 },
      { source: "porsche", target: "porsche-taycan", label: "produces", strength: 0.9 },
      { source: "lamborghini", target: "lamborghini-huracan", label: "produces", strength: 0.9 },
      { source: "bentley", target: "bentley-continental", label: "produces", strength: 0.9 },
      { source: "porsche-taycan", target: "electric-vehicle", label: "category", strength: 0.7 },
      { source: "lamborghini-huracan", target: "sports-car", label: "category", strength: 0.8 },
      { source: "bentley-continental", target: "luxury", label: "category", strength: 0.8 },
      { source: "skoda", target: "automotive", label: "operates_in", strength: 0.5 },
      { source: "seat", target: "automotive", label: "operates_in", strength: 0.5 },
    ],
  },
  "bmw": {
    nodes: [
      { id: "bmw-3-series", label: "BMW 3 Series", type: "product", description: "Compact executive sedan, BMW's best-selling model.", categories: ["Sedan", "Luxury"] },
      { id: "bmw-x5", label: "BMW X5", type: "product", description: "Mid-size luxury SUV by BMW.", categories: ["SUV", "Luxury"] },
      { id: "bmw-m3", label: "BMW M3", type: "product", description: "High-performance version of the 3 Series by BMW M Division.", categories: ["Sports Car", "Luxury"] },
      { id: "mini-cooper", label: "Mini Cooper", type: "product", description: "Iconic compact car by Mini.", categories: ["Compact"] },
      { id: "rolls-ghost", label: "Rolls-Royce Ghost", type: "product", description: "Ultra-luxury sedan by Rolls-Royce.", categories: ["Ultra-Luxury"] },
    ],
    links: [
      { source: "bmw", target: "bmw-3-series", label: "produces", strength: 0.9 },
      { source: "bmw", target: "bmw-x5", label: "produces", strength: 0.9 },
      { source: "bmw", target: "bmw-m3", label: "produces", strength: 0.9 },
      { source: "mini", target: "mini-cooper", label: "produces", strength: 0.9 },
      { source: "rolls-royce", target: "rolls-ghost", label: "produces", strength: 0.9 },
      { source: "bmw-m3", target: "sports-car", label: "category", strength: 0.8 },
      { source: "bmw-x5", target: "suv", label: "category", strength: 0.7 },
      { source: "rolls-ghost", target: "luxury", label: "category", strength: 1 },
    ],
  },
  "mercedes": {
    nodes: [
      { id: "mercedes-amg", label: "Mercedes-AMG", type: "subsidiary", description: "High-performance division of Mercedes-Benz.", industries: ["Automotive", "Performance"], parentCompany: "Mercedes-Benz Group" },
      { id: "maybach", label: "Mercedes-Maybach", type: "subsidiary", description: "Ultra-luxury sub-brand of Mercedes-Benz.", industries: ["Automotive", "Ultra-Luxury"], parentCompany: "Mercedes-Benz Group" },
      { id: "smart", label: "smart", type: "brand", description: "Microcar and subcompact brand, co-owned by Mercedes-Benz and Geely.", industries: ["Automotive", "Compact", "Electric Vehicles"], parentCompany: "Mercedes-Benz Group" },
      { id: "merc-s-class", label: "Mercedes-Benz S-Class", type: "product", description: "Full-size luxury sedan, flagship of Mercedes-Benz.", categories: ["Sedan", "Luxury"] },
      { id: "merc-g-class", label: "Mercedes-Benz G-Class", type: "product", description: "Luxury off-road SUV, iconic box design.", categories: ["SUV", "Luxury", "Off-road"] },
      { id: "merc-eq", label: "Mercedes-EQ", type: "product", description: "All-electric luxury sedan by Mercedes-Benz.", categories: ["Sedan", "Electric Vehicle", "Luxury"] },
    ],
    links: [
      { source: "mercedes", target: "mercedes-amg", label: "owns", strength: 1 },
      { source: "mercedes", target: "maybach", label: "owns", strength: 1 },
      { source: "mercedes", target: "smart", label: "owns", strength: 0.7 },
      { source: "mercedes", target: "merc-s-class", label: "produces", strength: 0.9 },
      { source: "mercedes", target: "merc-g-class", label: "produces", strength: 0.9 },
      { source: "mercedes", target: "merc-eq", label: "produces", strength: 0.9 },
      { source: "mercedes-amg", target: "sports-car", label: "category", strength: 0.8 },
      { source: "maybach", target: "luxury", label: "category", strength: 1 },
      { source: "merc-s-class", target: "luxury", label: "category", strength: 0.9 },
      { source: "merc-g-class", target: "luxury", label: "category", strength: 0.8 },
      { source: "merc-g-class", target: "off-road", label: "category", strength: 0.7 },
      { source: "merc-eq", target: "electric-vehicle", label: "category", strength: 0.7 },
    ],
  },
  "toyota": {
    nodes: [
      { id: "toyota-rav4", label: "Toyota RAV4", type: "product", description: "Compact crossover SUV, Toyota's best-selling SUV.", categories: ["SUV"] },
      { id: "land-cruiser", label: "Toyota Land Cruiser", type: "product", description: "Legendary off-road SUV by Toyota.", categories: ["SUV", "Off-road"] },
      { id: "tacoma", label: "Toyota Tacoma", type: "product", description: "Mid-size pickup truck, segment leader in North America.", categories: ["Pickup Truck"] },
      { id: "prius", label: "Toyota Prius", type: "product", description: "Hybrid-electric hatchback, pioneer of mass-market hybrid vehicles.", categories: ["Sedan", "Hybrid"] },
      { id: "lexus-rx", label: "Lexus RX", type: "product", description: "Mid-size luxury crossover SUV, Lexus's best-selling model.", categories: ["SUV", "Luxury"] },
    ],
    links: [
      { source: "toyota", target: "toyota-rav4", label: "produces", strength: 0.9 },
      { source: "toyota", target: "land-cruiser", label: "produces", strength: 0.9 },
      { source: "toyota", target: "tacoma", label: "produces", strength: 0.9 },
      { source: "toyota", target: "prius", label: "produces", strength: 0.9 },
      { source: "lexus", target: "lexus-rx", label: "produces", strength: 0.9 },
      { source: "suv", target: "toyota-rav4", label: "includes", strength: 0.7 },
      { source: "off-road", target: "land-cruiser", label: "includes", strength: 0.7 },
      { source: "pickup-truck", target: "tacoma", label: "includes", strength: 0.7 },
      { source: "lexus-rx", target: "luxury", label: "category", strength: 0.8 },
    ],
  },
  "honda": {
    nodes: [
      { id: "honda-cr-v", label: "Honda CR-V", type: "product", description: "Compact crossover SUV, one of the best-selling SUVs globally.", categories: ["SUV"] },
      { id: "honda-accord", label: "Honda Accord", type: "product", description: "Mid-size sedan, consistently one of the best-selling cars.", categories: ["Sedan"] },
      { id: "acura", label: "Acura", type: "brand", description: "Japanese luxury vehicle division of Honda.", industries: ["Automotive", "Luxury"], parentCompany: "Honda", founded: "1986" },
    ],
    links: [
      { source: "honda", target: "honda-cr-v", label: "produces", strength: 0.9 },
      { source: "honda", target: "honda-accord", label: "produces", strength: 0.9 },
      { source: "honda", target: "acura", label: "owns", strength: 1 },
      { source: "suv", target: "honda-cr-v", label: "includes", strength: 0.7 },
      { source: "sedan", target: "honda-accord", label: "includes", strength: 0.7 },
      { source: "acura", target: "luxury", label: "category", strength: 0.8 },
    ],
  },
  "hyundai-motor": {
    nodes: [
      { id: "hyundai-brand", label: "Hyundai", type: "brand", description: "South Korean automobile manufacturer, the core brand of Hyundai Motor Group.", industries: ["Automotive"], parentCompany: "Hyundai Motor Group", headquarters: "Seoul, South Korea", founded: "1967" },
      { id: "hyundai-tucson", label: "Hyundai Tucson", type: "product", description: "Compact crossover SUV by Hyundai.", categories: ["SUV"] },
      { id: "kia-sportage", label: "Kia Sportage", type: "product", description: "Compact crossover SUV by Kia.", categories: ["SUV"] },
      { id: "genesis-g80", label: "Genesis G80", type: "product", description: "Mid-size luxury sedan by Genesis.", categories: ["Sedan", "Luxury"] },
      { id: "hyundai-ioniq", label: "Hyundai Ioniq 5", type: "product", description: "All-electric compact crossover SUV by Hyundai.", categories: ["SUV", "Electric Vehicle"] },
    ],
    links: [
      { source: "hyundai-motor", target: "hyundai-brand", label: "owns", strength: 1 },
      { source: "hyundai-brand", target: "hyundai-tucson", label: "produces", strength: 0.9 },
      { source: "kia", target: "kia-sportage", label: "produces", strength: 0.9 },
      { source: "genesis", target: "genesis-g80", label: "produces", strength: 0.9 },
      { source: "hyundai-brand", target: "hyundai-ioniq", label: "produces", strength: 0.9 },
      { source: "suv", target: "hyundai-tucson", label: "includes", strength: 0.7 },
      { source: "suv", target: "kia-sportage", label: "includes", strength: 0.7 },
      { source: "luxury", target: "genesis-g80", label: "includes", strength: 0.7 },
      { source: "electric-vehicle", target: "hyundai-ioniq", label: "includes", strength: 0.7 },
    ],
  },
  "renault-nissan": {
    nodes: [
      { id: "nissan-leaf", label: "Nissan Leaf", type: "product", description: "Compact electric hatchback, one of the world's best-selling EVs.", categories: ["Electric Vehicle", "Compact"] },
      { id: "nissan-altima", label: "Nissan Altima", type: "product", description: "Mid-size sedan by Nissan.", categories: ["Sedan"] },
      { id: "renault-clio", label: "Renault Clio", type: "product", description: "Supermini car by Renault, one of Europe's best-sellers.", categories: ["Compact"] },
      { id: "mitsubishi-outlander", label: "Mitsubishi Outlander", type: "product", description: "Compact crossover SUV by Mitsubishi, also available as PHEV.", categories: ["SUV", "Electric Vehicle"] },
    ],
    links: [
      { source: "nissan", target: "nissan-leaf", label: "produces", strength: 0.9 },
      { source: "nissan", target: "nissan-altima", label: "produces", strength: 0.9 },
      { source: "renault", target: "renault-clio", label: "produces", strength: 0.9 },
      { source: "mitsubishi-motors", target: "mitsubishi-outlander", label: "produces", strength: 0.9 },
      { source: "electric-vehicle", target: "nissan-leaf", label: "includes", strength: 0.7 },
      { source: "sedan", target: "nissan-altima", label: "includes", strength: 0.7 },
    ],
  },
  "tesla": {
    nodes: [
      { id: "model-s", label: "Tesla Model S", type: "product", description: "Full-size luxury liftback sedan by Tesla, benchmark for EV performance.", categories: ["Sedan", "Luxury", "Electric Vehicle"] },
      { id: "model-x", label: "Tesla Model X", type: "product", description: "Mid-size luxury crossover SUV with falcon-wing doors.", categories: ["SUV", "Luxury", "Electric Vehicle"] },
      { id: "tesla-semi", label: "Tesla Semi", type: "product", description: "Class 8 all-electric semi-truck by Tesla.", categories: ["Commercial Vehicle", "Electric Vehicle"] },
    ],
    links: [
      { source: "tesla", target: "model-s", label: "produces", strength: 0.9 },
      { source: "tesla", target: "model-x", label: "produces", strength: 0.9 },
      { source: "tesla", target: "tesla-semi", label: "produces", strength: 0.9 },
      { source: "luxury", target: "model-s", label: "includes", strength: 0.7 },
      { source: "luxury", target: "model-x", label: "includes", strength: 0.7 },
      { source: "electric-vehicle", target: "model-s", label: "includes", strength: 0.7 },
      { source: "electric-vehicle", target: "model-x", label: "includes", strength: 0.7 },
      { source: "commercial-vehicle", target: "tesla-semi", label: "includes", strength: 0.7 },
    ],
  },
  "ford": {
    nodes: [
      { id: "bronco", label: "Ford Bronco", type: "product", description: "Off-road SUV by Ford.", categories: ["SUV", "Off-road"] },
      { id: "mustang-mach-e", label: "Ford Mustang Mach-E", type: "product", description: "Electric compact SUV by Ford.", categories: ["SUV", "Electric Vehicle"] },
      { id: "ford-explorer", label: "Ford Explorer", type: "product", description: "Mid-size SUV produced by Ford.", categories: ["SUV"] },
      { id: "ford-raptor", label: "Ford F-150 Raptor", type: "product", description: "High-performance off-road variant of the F-150.", categories: ["Pickup Truck", "Off-road"] },
    ],
    links: [
      { source: "ford", target: "bronco", label: "produces", strength: 0.9 },
      { source: "ford", target: "mustang-mach-e", label: "produces", strength: 0.9 },
      { source: "ford", target: "ford-explorer", label: "produces", strength: 0.9 },
      { source: "ford", target: "ford-raptor", label: "produces", strength: 0.9 },
      { source: "suv", target: "bronco", label: "includes", strength: 0.7 },
      { source: "suv", target: "mustang-mach-e", label: "includes", strength: 0.7 },
      { source: "suv", target: "ford-explorer", label: "includes", strength: 0.7 },
      { source: "electric-vehicle", target: "mustang-mach-e", label: "includes", strength: 0.7 },
      { source: "off-road", target: "bronco", label: "includes", strength: 0.7 },
    ],
  },
  "gm": {
    nodes: [
      { id: "silverado", label: "Chevrolet Silverado", type: "product", description: "Full-size pickup truck produced by Chevrolet.", categories: ["Pickup Truck"] },
      { id: "chevy-tahoe", label: "Chevrolet Tahoe", type: "product", description: "Full-size SUV produced by Chevrolet.", categories: ["SUV"] },
      { id: "gmc-sierra", label: "GMC Sierra", type: "product", description: "Full-size pickup truck by GMC.", categories: ["Pickup Truck"] },
      { id: "cadillac-escalade", label: "Cadillac Escalade", type: "product", description: "Full-size luxury SUV by Cadillac.", categories: ["SUV", "Luxury"] },
      { id: "hummer-ev", label: "GMC Hummer EV", type: "product", description: "All-electric pickup truck and SUV by GMC.", categories: ["Electric Vehicle", "Pickup Truck"] },
    ],
    links: [
      { source: "chevrolet", target: "silverado", label: "produces", strength: 0.9 },
      { source: "chevrolet", target: "chevy-tahoe", label: "produces", strength: 0.9 },
      { source: "gmc", target: "gmc-sierra", label: "produces", strength: 0.9 },
      { source: "gmc", target: "hummer-ev", label: "produces", strength: 0.9 },
      { source: "cadillac", target: "cadillac-escalade", label: "produces", strength: 0.9 },
      { source: "pickup-truck", target: "silverado", label: "includes", strength: 0.7 },
      { source: "pickup-truck", target: "gmc-sierra", label: "includes", strength: 0.7 },
      { source: "pickup-truck", target: "hummer-ev", label: "includes", strength: 0.7 },
      { source: "suv", target: "chevy-tahoe", label: "includes", strength: 0.7 },
      { source: "luxury", target: "cadillac-escalade", label: "includes", strength: 0.7 },
      { source: "electric-vehicle", target: "hummer-ev", label: "includes", strength: 0.7 },
    ],
  },
  "jeep": {
    nodes: [
      { id: "jeep-wrangler", label: "Jeep Wrangler", type: "product", description: "Compact/mid-size off-road SUV produced by Jeep.", categories: ["SUV", "Off-road"] },
      { id: "jeep-compass", label: "Jeep Compass", type: "product", description: "Compact crossover SUV produced by Jeep.", categories: ["SUV", "Compact"] },
      { id: "jeep-gladiator", label: "Jeep Gladiator", type: "product", description: "Mid-size pickup truck produced by Jeep.", categories: ["Pickup Truck"] },
      { id: "jeep-cherokee", label: "Jeep Cherokee", type: "product", description: "Compact SUV formerly produced by Jeep.", categories: ["SUV"] },
    ],
    links: [
      { source: "jeep", target: "jeep-wrangler", label: "produces", strength: 0.9 },
      { source: "jeep", target: "jeep-compass", label: "produces", strength: 0.9 },
      { source: "jeep", target: "jeep-gladiator", label: "produces", strength: 0.9 },
      { source: "jeep", target: "jeep-cherokee", label: "produces", strength: 0.9 },
      { source: "off-road", target: "jeep-wrangler", label: "includes", strength: 0.8 },
      { source: "suv", target: "jeep-compass", label: "includes", strength: 0.7 },
      { source: "pickup-truck", target: "jeep-gladiator", label: "includes", strength: 0.7 },
    ],
  },
  "dodge": {
    nodes: [
      { id: "dodge-charger", label: "Dodge Charger", type: "product", description: "Full-size sedan/muscle car by Dodge.", categories: ["Sedan", "Muscle Car"] },
      { id: "dodge-challenger", label: "Dodge Challenger", type: "product", description: "Pony car/muscle car by Dodge.", categories: ["Muscle Car"] },
    ],
    links: [
      { source: "dodge", target: "dodge-charger", label: "produces", strength: 0.9 },
      { source: "dodge", target: "dodge-challenger", label: "produces", strength: 0.9 },
      { source: "muscle-car", target: "dodge-charger", label: "includes", strength: 0.7 },
      { source: "muscle-car", target: "dodge-challenger", label: "includes", strength: 0.7 },
    ],
  },
  "chrysler": {
    nodes: [
      { id: "chrysler-300", label: "Chrysler 300", type: "product", description: "Full-size luxury sedan by Chrysler.", categories: ["Sedan", "Luxury"] },
      { id: "chrysler-pacifica", label: "Chrysler Pacifica", type: "product", description: "Minivan by Chrysler, also available as a plug-in hybrid.", categories: ["Minivan"] },
      { id: "minivan", label: "Minivan", type: "category", description: "Multi-purpose vehicle designed for passenger and cargo capacity." },
    ],
    links: [
      { source: "chrysler", target: "chrysler-300", label: "produces", strength: 0.9 },
      { source: "chrysler", target: "chrysler-pacifica", label: "produces", strength: 0.9 },
      { source: "minivan", target: "chrysler-pacifica", label: "includes", strength: 0.7 },
      { source: "luxury", target: "chrysler-300", label: "includes", strength: 0.7 },
    ],
  },
  "fiat": {
    nodes: [
      { id: "fiat-500", label: "Fiat 500", type: "product", description: "Compact city car, icon of Italian automotive design.", categories: ["Compact", "City Car"] },
      { id: "fiat-500e", label: "Fiat 500e", type: "product", description: "All-electric version of the Fiat 500.", categories: ["Compact", "Electric Vehicle"] },
      { id: "city-car", label: "City Car", type: "category", description: "Compact automobiles designed for urban use." },
    ],
    links: [
      { source: "fiat", target: "fiat-500", label: "produces", strength: 0.9 },
      { source: "fiat", target: "fiat-500e", label: "produces", strength: 0.9 },
      { source: "fiat", target: "city-car", label: "category", strength: 0.7 },
      { source: "city-car", target: "fiat-500", label: "includes", strength: 0.7 },
      { source: "electric-vehicle", target: "fiat-500e", label: "includes", strength: 0.7 },
    ],
  },
  "maserati": {
    nodes: [
      { id: "maserati-mc20", label: "Maserati MC20", type: "product", description: "Mid-engine sports car by Maserati.", categories: ["Sports Car", "Luxury"] },
      { id: "maserati-levant", label: "Maserati Levante", type: "product", description: "Luxury crossover SUV by Maserati.", categories: ["SUV", "Luxury"] },
    ],
    links: [
      { source: "maserati", target: "maserati-mc20", label: "produces", strength: 0.9 },
      { source: "maserati", target: "maserati-levant", label: "produces", strength: 0.9 },
      { source: "maserati", target: "sports-car", label: "category", strength: 0.8 },
      { source: "sports-car", target: "maserati-mc20", label: "includes", strength: 0.7 },
      { source: "suv", target: "maserati-levant", label: "includes", strength: 0.7 },
    ],
  },
  "alfa-romeo": {
    nodes: [
      { id: "giulia", label: "Alfa Romeo Giulia", type: "product", description: "Compact executive sedan by Alfa Romeo.", categories: ["Sedan", "Luxury"] },
      { id: "stelvio", label: "Alfa Romeo Stelvio", type: "product", description: "Compact luxury SUV by Alfa Romeo.", categories: ["SUV", "Luxury"] },
    ],
    links: [
      { source: "alfa-romeo", target: "giulia", label: "produces", strength: 0.9 },
      { source: "alfa-romeo", target: "stelvio", label: "produces", strength: 0.9 },
      { source: "suv", target: "stelvio", label: "includes", strength: 0.7 },
    ],
  },
  "chevrolet": {
    nodes: [
      { id: "camaro", label: "Chevrolet Camaro", type: "product", description: "Muscle car/pony car by Chevrolet.", categories: ["Muscle Car"] },
      { id: "bolt", label: "Chevrolet Bolt EV", type: "product", description: "Compact electric hatchback by Chevrolet.", categories: ["Electric Vehicle", "Compact"] },
      { id: "chevy-suburban", label: "Chevrolet Suburban", type: "product", description: "Full-size SUV by Chevrolet, longest-running nameplate.", categories: ["SUV"] },
    ],
    links: [
      { source: "chevrolet", target: "camaro", label: "produces", strength: 0.9 },
      { source: "chevrolet", target: "bolt", label: "produces", strength: 0.9 },
      { source: "chevrolet", target: "chevy-suburban", label: "produces", strength: 0.9 },
      { source: "muscle-car", target: "camaro", label: "includes", strength: 0.8 },
      { source: "electric-vehicle", target: "bolt", label: "includes", strength: 0.7 },
      { source: "suv", target: "chevy-suburban", label: "includes", strength: 0.7 },
    ],
  },
  "gmc": {
    nodes: [
      { id: "gmc-terrain", label: "GMC Terrain", type: "product", description: "Compact crossover SUV by GMC.", categories: ["SUV", "Compact"] },
      { id: "gmc-yukon", label: "GMC Yukon", type: "product", description: "Full-size SUV by GMC.", categories: ["SUV"] },
    ],
    links: [
      { source: "gmc", target: "gmc-terrain", label: "produces", strength: 0.9 },
      { source: "gmc", target: "gmc-yukon", label: "produces", strength: 0.9 },
      { source: "suv", target: "gmc-terrain", label: "includes", strength: 0.7 },
      { source: "suv", target: "gmc-yukon", label: "includes", strength: 0.7 },
    ],
  },
  "cadillac": {
    nodes: [
      { id: "cadillac-lyriq", label: "Cadillac Lyriq", type: "product", description: "All-electric luxury SUV by Cadillac.", categories: ["SUV", "Luxury", "Electric Vehicle"] },
      { id: "cadillac-ct5", label: "Cadillac CT5", type: "product", description: "Mid-size luxury sedan by Cadillac.", categories: ["Sedan", "Luxury"] },
    ],
    links: [
      { source: "cadillac", target: "cadillac-lyriq", label: "produces", strength: 0.9 },
      { source: "cadillac", target: "cadillac-ct5", label: "produces", strength: 0.9 },
      { source: "electric-vehicle", target: "cadillac-lyriq", label: "includes", strength: 0.7 },
      { source: "luxury", target: "cadillac-ct5", label: "includes", strength: 0.7 },
    ],
  },
  "audi": {
    nodes: [
      { id: "audi-q5", label: "Audi Q5", type: "product", description: "Compact luxury crossover SUV by Audi.", categories: ["SUV", "Luxury"] },
      { id: "audi-e-tron", label: "Audi e-tron", type: "product", description: "All-electric SUV by Audi.", categories: ["SUV", "Electric Vehicle", "Luxury"] },
    ],
    links: [
      { source: "audi", target: "audi-q5", label: "produces", strength: 0.9 },
      { source: "audi", target: "audi-e-tron", label: "produces", strength: 0.9 },
      { source: "suv", target: "audi-q5", label: "includes", strength: 0.7 },
      { source: "electric-vehicle", target: "audi-e-tron", label: "includes", strength: 0.7 },
      { source: "luxury", target: "audi-q5", label: "includes", strength: 0.7 },
    ],
  },
  "porsche": {
    nodes: [
      { id: "porsche-cayenne", label: "Porsche Cayenne", type: "product", description: "Mid-size luxury crossover SUV by Porsche.", categories: ["SUV", "Luxury"] },
      { id: "porsche-macan", label: "Porsche Macan", type: "product", description: "Compact luxury crossover SUV by Porsche.", categories: ["SUV", "Luxury"] },
    ],
    links: [
      { source: "porsche", target: "porsche-cayenne", label: "produces", strength: 0.9 },
      { source: "porsche", target: "porsche-macan", label: "produces", strength: 0.9 },
      { source: "suv", target: "porsche-cayenne", label: "includes", strength: 0.7 },
      { source: "luxury", target: "porsche-cayenne", label: "includes", strength: 0.7 },
      { source: "luxury", target: "porsche-macan", label: "includes", strength: 0.7 },
    ],
  },
  "lamborghini": {
    nodes: [
      { id: "lambo-urus", label: "Lamborghini Urus", type: "product", description: "Super SUV by Lamborghini, their best-selling model.", categories: ["SUV", "Ultra-Luxury"] },
    ],
    links: [
      { source: "lamborghini", target: "lambo-urus", label: "produces", strength: 0.9 },
      { source: "luxury", target: "lambo-urus", label: "includes", strength: 0.8 },
    ],
  },
  "lexus": {
    nodes: [
      { id: "lexus-rx-expand", label: "Lexus RX", type: "product", description: "Mid-size luxury crossover SUV, Lexus's best-selling model.", categories: ["SUV", "Luxury"] },
      { id: "lexus-is", label: "Lexus IS", type: "product", description: "Compact executive sedan by Lexus.", categories: ["Sedan", "Luxury"] },
    ],
    links: [
      { source: "lexus", target: "lexus-rx-expand", label: "produces", strength: 0.9 },
      { source: "lexus", target: "lexus-is", label: "produces", strength: 0.9 },
      { source: "luxury", target: "lexus-is", label: "includes", strength: 0.7 },
    ],
  },
  "kia": {
    nodes: [
      { id: "kia-ev6", label: "Kia EV6", type: "product", description: "All-electric compact crossover SUV by Kia.", categories: ["SUV", "Electric Vehicle"] },
      { id: "kia-telluride", label: "Kia Telluride", type: "product", description: "Mid-size SUV by Kia.", categories: ["SUV"] },
    ],
    links: [
      { source: "kia", target: "kia-ev6", label: "produces", strength: 0.9 },
      { source: "kia", target: "kia-telluride", label: "produces", strength: 0.9 },
      { source: "electric-vehicle", target: "kia-ev6", label: "includes", strength: 0.7 },
      { source: "suv", target: "kia-telluride", label: "includes", strength: 0.7 },
    ],
  },
  "subaru": {
    nodes: [
      { id: "subaru-outback", label: "Subaru Outback", type: "product", description: "Mid-size crossover SUV with off-road capability.", categories: ["SUV", "Off-road"] },
      { id: "subaru-wrx", label: "Subaru WRX", type: "product", description: "Compact sports sedan by Subaru.", categories: ["Sedan", "Sports"] },
    ],
    links: [
      { source: "subaru", target: "subaru-outback", label: "produces", strength: 0.9 },
      { source: "subaru", target: "subaru-wrx", label: "produces", strength: 0.9 },
      { source: "off-road", target: "subaru-outback", label: "includes", strength: 0.7 },
    ],
  },
  "suv": {
    nodes: [
      { id: "toyota-rav4-suv", label: "Toyota RAV4", type: "product", description: "Compact crossover SUV, Toyota's best-selling SUV.", categories: ["SUV"] },
      { id: "honda-cr-v-suv", label: "Honda CR-V", type: "product", description: "Compact crossover SUV, one of the best-selling SUVs globally.", categories: ["SUV"] },
    ],
    links: [
      { source: "toyota", target: "toyota-rav4-suv", label: "produces", strength: 0.9 },
      { source: "honda", target: "honda-cr-v-suv", label: "produces", strength: 0.9 },
      { source: "suv", target: "toyota-rav4-suv", label: "includes", strength: 0.7 },
      { source: "suv", target: "honda-cr-v-suv", label: "includes", strength: 0.7 },
    ],
  },
  "pickup-truck": {
    nodes: [
      { id: "tacoma-pt", label: "Toyota Tacoma", type: "product", description: "Mid-size pickup truck, segment leader in North America.", categories: ["Pickup Truck"] },
      { id: "colorado", label: "Chevrolet Colorado", type: "product", description: "Mid-size pickup truck by Chevrolet.", categories: ["Pickup Truck"] },
      { id: "frontier", label: "Nissan Frontier", type: "product", description: "Mid-size pickup truck by Nissan.", categories: ["Pickup Truck"] },
    ],
    links: [
      { source: "toyota", target: "tacoma-pt", label: "produces", strength: 0.9 },
      { source: "chevrolet", target: "colorado", label: "produces", strength: 0.9 },
      { source: "nissan", target: "frontier", label: "produces", strength: 0.9 },
      { source: "pickup-truck", target: "tacoma-pt", label: "includes", strength: 0.7 },
      { source: "pickup-truck", target: "colorado", label: "includes", strength: 0.7 },
      { source: "pickup-truck", target: "frontier", label: "includes", strength: 0.7 },
    ],
  },
  "luxury": {
    nodes: [
      { id: "vw-group-lux", label: "Volkswagen Group", type: "company", description: "German multinational automotive manufacturing company, the largest automaker in Europe.", industries: ["Automotive", "Luxury"], headquarters: "Wolfsburg, Germany", founded: "1937" },
    ],
    links: [],
  },
  "electric-vehicle": {
    nodes: [
      { id: "rivian", label: "Rivian", type: "company", description: "American electric vehicle manufacturer focused on adventure vehicles.", industries: ["Automotive", "Electric Vehicles"], headquarters: "Irvine, California, USA", founded: "2009" },
      { id: "lucid", label: "Lucid Motors", type: "company", description: "American luxury electric vehicle manufacturer.", industries: ["Automotive", "Electric Vehicles", "Luxury"], headquarters: "Newark, California, USA", founded: "2007" },
      { id: "byd", label: "BYD Auto", type: "company", description: "Chinese automobile manufacturer, world's largest EV seller by volume.", industries: ["Automotive", "Electric Vehicles"], headquarters: "Shenzhen, China", founded: "2003" },
    ],
    links: [
      { source: "rivian", target: "electric-vehicle", label: "operates_in", strength: 0.8 },
      { source: "lucid", target: "electric-vehicle", label: "operates_in", strength: 0.8 },
      { source: "byd", target: "electric-vehicle", label: "operates_in", strength: 0.8 },
      { source: "lucid", target: "luxury", label: "operates_in", strength: 0.7 },
    ],
  },
  "sports-car": {
    nodes: [
      { id: "ferrari", label: "Ferrari", type: "company", description: "Italian luxury sports car manufacturer.", industries: ["Automotive", "Ultra-Luxury", "Performance"], headquarters: "Maranello, Italy", founded: "1939" },
      { id: "mclaren", label: "McLaren", type: "company", description: "British luxury automotive manufacturer focused on high-performance vehicles.", industries: ["Automotive", "Performance", "Ultra-Luxury"], headquarters: "Woking, England", founded: "1985" },
      { id: "aston-martin", label: "Aston Martin", type: "company", description: "British luxury sports car and grand tourer manufacturer.", industries: ["Automotive", "Luxury", "Performance"], headquarters: "Gaydon, England", founded: "1913" },
    ],
    links: [
      { source: "ferrari", target: "sports-car", label: "operates_in", strength: 0.9 },
      { source: "ferrari", target: "luxury", label: "operates_in", strength: 0.9 },
      { source: "mclaren", target: "sports-car", label: "operates_in", strength: 0.9 },
      { source: "aston-martin", target: "sports-car", label: "operates_in", strength: 0.8 },
      { source: "aston-martin", target: "luxury", label: "operates_in", strength: 0.8 },
    ],
  },
};

export async function getInitialGraph(): Promise<GraphResponse> {
  await delay(600);
  return {
    nodes: INITIAL_NODES.map(cloneNode),
    links: INITIAL_LINKS.map(cloneLink),
    meta: {
      total_nodes: INITIAL_NODES.length,
      total_links: INITIAL_LINKS.length,
      seed_node: "automotive",
    },
  };
}

export async function expandNode(nodeId: string): Promise<ExpandResponse> {
  const expansion = EXPANSIONS[nodeId];
  if (!expansion) {
    return { new_nodes: [], new_links: [], expanded_from: nodeId };
  }
  await delay(1200 + Math.random() * 800);
  return {
    new_nodes: expansion.nodes.map(cloneNode),
    new_links: expansion.links.map(cloneLink),
    expanded_from: nodeId,
  };
}
